name: cielo_ecommerce
description: Pacote para criar pagamentos usando o SDK da API Cielo e-Commerce. Para mais informações acesse a documentação oficial da Cielo e-Commerce para desenvolvedores.
version: 1.0.2
homepage: https://github.com/weldonsouza/cielo_ecommerce

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
